# The URL the site will be built for
base_url = "https://nmbr7.github.io"

title = "nmbr_7"
description = "Security Enthusiast interested in System/Web security, CTFer, Student"
generate_rss = true

# Go through every links in all content and check if the links are valid
check_external_links = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

[extra]
    author = "Suhailr7"
